name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://alphaone-my.sharepoint.cn/personal/6yunorg_vip_tg/_layouts/15/download.aspx?UniqueId=0e085134-a8c7-4eb3-9fae-27750ca5db5b&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvYWxwaGFvbmUtbXkuc2hhcmVwb2ludC5jbkAzYjFjODFiMS1kMTU2LTRhZjktYjE2OS1hZTA4MTI4YzAzOTYiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjE0MjYzMjU4IiwiZXhwIjoiMTYxNDI2Njg1OCIsImVuZHBvaW50dXJsIjoiTEVLRXg2NUJmZWY1Z2xrUDVFUnZQcU9lYUpLYStoVlc5RnM1OHZ2R21FUT0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE0NSIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiTUdFd1l6QXdaakl0WmpWbU5TMDBaRE0yTFdJeU5qa3RPRFV4WlRGaU1UZzJZV0l4IiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6Ik9HWTBNamN5WkdFdE5qazFPQzAwWlRBMExXSXpaRGt0TldJNVptWTJOemM0T1RjMSIsImFwcF9kaXNwbGF5bmFtZSI6InotMzU3Mzk0LXl1bjYiLCJhcHBpZCI6ImNjNzJkZjdhLTE3ZmQtNDEwNi1hMjEzLTI3YTE4M2Q2MDJiOCIsInRpZCI6IjNiMWM4MWIxLWQxNTYtNGFmOS1iMTY5LWFlMDgxMjhjMDM5NiIsInVwbiI6IjZ5dW5vcmdAdmlwLnRnIiwicHVpZCI6IjEwMDMzMjMwQzU3MTZGQzgiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMzIzMGM1NzE2ZmM4QGxpdmUuY29tIiwic2NwIjoiYWxsZmlsZXMud3JpdGUiLCJ0dCI6IjIiLCJ1c2VQZXJzaXN0ZW50Q29va2llIjpudWxsfQ.TjFkMzlpZmNwQUhFcnA2MW40TUU4VWxPYitnQ0lkenhPaGdrN1BoRTRNUT0&ApiVersion=2.0
  ROM_NAME: Flyme
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              mkdir final
              zip -r final/GSI.zip /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
       
       - name: Upload GSI to BitSend
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./cowtransfer-uploader/GSI.zip

         
            
